# how to use
# ansible-playbook -i inventory playbooks/setup_node.yaml -v or -vvv for more information
# execute tasks in sudo level
- name: Setting up Jenkins agent
  hosts: agents # runs commands in agent present within the inventory file
  any_errors_fatal: true # aborts the while execution if host fails
  become: yes 
  tasks:
    - name: Installing Java required by agent
      apt:
        update_cache: yes
        name: openjdk-21-jdk
        state: present

    - name: Report installed Java version
      command: java --version
      register: java_variable
      changed_when: false

    - name: Show installed Java version
      debug:
        var: java_variable.stdout_lines

    